/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppReplayRouteImport } from './routes/_app/replay'
import { Route as AppCorrectionRouteImport } from './routes/_app/correction'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppBluetoothRouteImport } from './routes/_app/bluetooth'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrectionRoute = AppCorrectionRouteImport.update({
  id: '/correction',
  path: '/correction',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppBluetoothRoute = AppBluetoothRouteImport.update({
  id: '/bluetooth',
  path: '/bluetooth',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/bluetooth': typeof AppBluetoothRoute
  '/compare': typeof AppCompareRoute
  '/correction': typeof AppCorrectionRoute
  '/replay': typeof AppReplayRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/bluetooth': typeof AppBluetoothRoute
  '/compare': typeof AppCompareRoute
  '/correction': typeof AppCorrectionRoute
  '/replay': typeof AppReplayRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/bluetooth': typeof AppBluetoothRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/correction': typeof AppCorrectionRoute
  '/_app/replay': typeof AppReplayRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bluetooth'
    | '/compare'
    | '/correction'
    | '/replay'
    | '/sessions'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/bluetooth'
    | '/compare'
    | '/correction'
    | '/replay'
    | '/sessions'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/bluetooth'
    | '/_app/compare'
    | '/_app/correction'
    | '/_app/replay'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replay': {
      id: '/_app/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correction': {
      id: '/_app/correction'
      path: '/correction'
      fullPath: '/correction'
      preLoaderRoute: typeof AppCorrectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bluetooth': {
      id: '/_app/bluetooth'
      path: '/bluetooth'
      fullPath: '/bluetooth'
      preLoaderRoute: typeof AppBluetoothRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBluetoothRoute: typeof AppBluetoothRoute
  AppCompareRoute: typeof AppCompareRoute
  AppCorrectionRoute: typeof AppCorrectionRoute
  AppReplayRoute: typeof AppReplayRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBluetoothRoute: AppBluetoothRoute,
  AppCompareRoute: AppCompareRoute,
  AppCorrectionRoute: AppCorrectionRoute,
  AppReplayRoute: AppReplayRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
